export type Restaurant = { id: string; name: string; cuisine: string; categories?: string[]; city: string; state?: string; currency?: "USD" | "GBP"; neighborhood: string; address: string; price: number | null; image: string; demo: boolean; sourceUrl?: string; website?: string; lat?: number; lon?: number; listed?: number; yes: number; count: number; food: number; service: number; value: number; lastVisit?: string; excluded: number; description: string; dish: string; };
export type DirectoryVenue = { id:string;name:string;state:string;city:string;address:string;categories:string[];postcode?:string;neighborhood?:string;lat:number;lon:number;website?:string };
export type DirectoryData = { importedAt:string;sourceUrl:string;licenseUrl:string;snapshots:{state:string;name:string;imported:number}[];venues:DirectoryVenue[] };
export function directoryRestaurants(data:DirectoryData):Restaurant[] { return data.venues.map(v=>({...v,cuisine:v.categories[0],neighborhood:v.neighborhood??v.city,address:[v.address,v.city,v.state,v.postcode].filter(Boolean).join(", "),price:null,currency:"USD",demo:false,image:"",yes:0,count:0,food:0,service:0,value:0,excluded:0,description:`${v.categories.filter(x=>x!=="Other").join(" · ")||"Food venue"} in ${v.city}. Listed in OpenStreetMap; check the venue for current details.`,dish:"",sourceUrl:`https://www.openstreetmap.org/${v.id.replace(/^osm-(node|way|relation)-(\d+)$/,"$1/$2")}`})); }
export function mergeRestaurants(directory:Restaurant[], contributions:Restaurant[], samples=false) {
  const merged=new Map(directory.map(r=>[r.id,r]));
  for(const r of contributions)merged.set(r.id,{...merged.get(r.id),...r});
  return [...merged.values(),...(samples?sampleRestaurants:[])];
}
export function currencySymbol(r?:Restaurant) {return r?.currency === "GBP" || r?.demo || (r && !r.state) ? "£" : "$";}
export function mealPrice(r:Restaurant) {return r.price === null ? "Price not reported" : `${currencySymbol(r)}${r.price}`;}
export function restaurantSearchText(r:Restaurant) {return `${r.name} ${r.cuisine} ${(r.categories??[]).join(" ")} ${r.city} ${r.state??""} ${r.state==="NJ"?"New Jersey":r.state==="NY"?"New York":r.state==="CA"?"California":""} ${r.neighborhood} ${r.description} ${r.dish} ${r.address}`.toLowerCase();}
export const sampleRestaurants: Restaurant[] = [
{id:"sample-casa",name:"Casa Farina",cuisine:"Italian",city:"London",neighborhood:"Shoreditch",address:"Illustrative location · no real address",price:24,image:"pasta",demo:true,yes:40,count:44,food:4.6,service:4.2,value:4.5,excluded:3,description:"A little neighborhood pasta kitchen. Slow sauces, generous portions, and a table you’ll want to linger at.",dish:"Pappardelle with slow-cooked ragù"},
{id:"sample-kumo",name:"Kumo Kitchen",cuisine:"Japanese",city:"London",neighborhood:"Soho",address:"Illustrative location · no real address",price:38,image:"sushi",demo:true,yes:28,count:32,food:4.7,service:4.4,value:3.8,excluded:2,description:"Seasonal sushi and small plates in an intimate setting. Best for an unhurried evening with a friend.",dish:"Chef’s seasonal sushi selection"},
{id:"sample-sunday",name:"Sunday & Co.",cuisine:"Café",city:"London",neighborhood:"Notting Hill",address:"Illustrative location · no real address",price:16,image:"cafe",demo:true,yes:45,count:48,food:4.4,service:4.6,value:4.7,excluded:1,description:"Good coffee, flaky pastries, and a sunny corner table. A small pleasure for a slow Sunday morning.",dish:"Almond croissant and a flat white"},
];
export type Review = {id:string;restaurant_id:string;visit_date:string;dish:string;spend?:number;return_visit:number;food:number;service:number;value:number;note:string;incentivized:number;relationship:number;status:string;decision_note?:string;created_at:string;};
export type Profile = { cuisine: string; budget: number; priority: string };
export const defaultProfile: Profile = { cuisine:"Any",budget:40,priority:"food" };
export function returnPercent(r:Restaurant) { return r.count ? Math.round(100*r.yes/r.count) : null; }
export function confidenceInterval(yes:number,count:number) { if(!count)return null; const p=yes/count,z=1.96,d=1+z*z/count,c=(p+z*z/(2*count))/d,h=z*Math.sqrt((p*(1-p)+z*z/(4*count))/count)/d; return [Math.round((c-h)*100),Math.round((c+h)*100)]; }
export function tasteFit(r:Restaurant,p:Profile) { const cuisine=p.cuisine==="Any"||(r.categories??[r.cuisine]).includes(p.cuisine);const budget=r.currency === "USD" && r.price!==null && r.price<=p.budget; const metric=r[p.priority as "food"|"service"|"value"]||0;return {score:(cuisine?40:0)+(budget?30:0)+metric*6, reasons:[...(p.cuisine!=="Any"&&cuisine?[`${p.cuisine} is your kind of food`]:[]),...(budget?[`Within your $${p.budget} budget`]:[]),...(r.count>=5&&metric>=4?[`Strong ${p.priority} feedback`]:[]),...(r.price===null?["Meal price not reported yet"]:[])]}; }
