export type Restaurant = { id: string; name: string; cuisine: string; city: string; neighborhood: string; address: string; price: number; image: string; demo: boolean; listed?: number; yes: number; count: number; food: number; service: number; value: number; lastVisit?: string; excluded: number; description: string; dish: string; };
export const sampleRestaurants: Restaurant[] = [
{id:"sample-casa",name:"Casa Farina",cuisine:"Italian",city:"London",neighborhood:"Shoreditch",address:"Illustrative location · no real address",price:24,image:"pasta",demo:true,yes:40,count:44,food:4.6,service:4.2,value:4.5,excluded:3,description:"A little neighborhood pasta kitchen. Slow sauces, generous portions, and a table you’ll want to linger at.",dish:"Pappardelle with slow-cooked ragù"},
{id:"sample-kumo",name:"Kumo Kitchen",cuisine:"Japanese",city:"London",neighborhood:"Soho",address:"Illustrative location · no real address",price:38,image:"sushi",demo:true,yes:28,count:32,food:4.7,service:4.4,value:3.8,excluded:2,description:"Seasonal sushi and small plates in an intimate setting. Best for an unhurried evening with a friend.",dish:"Chef’s seasonal sushi selection"},
{id:"sample-sunday",name:"Sunday & Co.",cuisine:"Café",city:"London",neighborhood:"Notting Hill",address:"Illustrative location · no real address",price:16,image:"cafe",demo:true,yes:45,count:48,food:4.4,service:4.6,value:4.7,excluded:1,description:"Good coffee, flaky pastries, and a sunny corner table. A small pleasure for a slow Sunday morning.",dish:"Almond croissant and a flat white"},
];
export type Review = {id:string;restaurant_id:string;visit_date:string;dish:string;spend?:number;return_visit:number;food:number;service:number;value:number;note:string;incentivized:number;relationship:number;status:string;decision_note?:string;created_at:string;};
export type Profile = { cuisine: string; budget: number; priority: string };
export const defaultProfile: Profile = { cuisine:"Any",budget:40,priority:"food" };
export function returnPercent(r:Restaurant) { return r.count ? Math.round(100*r.yes/r.count) : null; }
export function confidenceInterval(yes:number,count:number) { if(!count)return null; const p=yes/count,z=1.96,d=1+z*z/count,c=(p+z*z/(2*count))/d,h=z*Math.sqrt((p*(1-p)+z*z/(4*count))/count)/d; return [Math.round((c-h)*100),Math.round((c+h)*100)]; }
export function tasteFit(r:Restaurant,p:Profile) { const cuisine=p.cuisine==="Any"||p.cuisine===r.cuisine;const budget=r.price<=p.budget; const metric=r[p.priority as "food"|"service"|"value"]||0;return {score:(cuisine?40:0)+(budget?30:0)+metric*6, reasons:[...(p.cuisine!=="Any"&&cuisine?[`${p.cuisine} is your kind of food`]:[]),...(budget?[`Within your £${p.budget} budget`]:[]),...(r.count>=5&&metric>=4?[`Strong ${p.priority} feedback`]:[])]}; }
