import { sqliteTable, text, integer, real, primaryKey, index, uniqueIndex } from "drizzle-orm/sqlite-core";
export const restaurants = sqliteTable("restaurants", {
  id: text("id").primaryKey(), creator: text("creator").notNull(), name: text("name").notNull(), cuisine: text("cuisine").notNull(), city: text("city").notNull(), neighborhood: text("neighborhood").notNull(), address: text("address").notNull(), price: real("price").notNull(), listed: integer("listed").notNull().default(0), createdAt: text("created_at").notNull(),
});
export const profiles = sqliteTable("profiles", { userId: text("user_id").primaryKey(), cuisine: text("cuisine").notNull(), budget: integer("budget").notNull(), priority: text("priority").notNull() });
export const saved = sqliteTable("saved", { userId: text("user_id").notNull(), restaurantId: text("restaurant_id").notNull(), createdAt: text("created_at").notNull() }, t => [primaryKey({ columns: [t.userId, t.restaurantId] })]);
export const reviews = sqliteTable("reviews", {
  id: text("id").primaryKey(), userId: text("user_id").notNull(), restaurantId: text("restaurant_id").notNull(), visitDate: text("visit_date").notNull(), dish: text("dish").notNull(), spend: real("spend").notNull(), returnVisit: integer("return_visit").notNull(), food: integer("food").notNull(), service: integer("service").notNull(), value: integer("value").notNull(), note: text("note").notNull(), incentivized: integer("incentivized").notNull(), relationship: integer("relationship").notNull(), receiptKey: text("receipt_key").notNull(), receiptHash: text("receipt_hash").notNull(), status: text("status").notNull().default("pending"), decisionNote: text("decision_note"), moderator: text("moderator"), decidedAt: text("decided_at"), createdAt: text("created_at").notNull(),
}, t => [uniqueIndex("idx_reviews_receipt_hash").on(t.receiptHash), uniqueIndex("idx_reviews_user_restaurant_date").on(t.userId,t.restaurantId,t.visitDate), index("idx_reviews_restaurant_status_date").on(t.restaurantId,t.status,t.visitDate), index("idx_reviews_user_created").on(t.userId,t.createdAt), index("idx_reviews_status_created").on(t.status,t.createdAt)]);
